[package]
name = "abstract_factory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macos-gui = "./macos-gui"
windows-gui = "./windows-gui"